# Generated by Django 4.2.2 on 2023-08-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_user_account_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
