# Generated by Django 4.2.2 on 2023-08-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_user_account_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(max_length=50)),
                ('menu_item_name', models.CharField(max_length=50)),
                ('offer', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('details', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'offer',
            },
        ),
    ]
