# Generated by Django 4.2.2 on 2023-09-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=50)),
                ('menu_name', models.CharField(max_length=50)),
                ('menu_item_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('cooking_time', models.TimeField()),
                ('status', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'food_item',
            },
        ),
    ]
