# Generated by Django 4.2.2 on 2023-09-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_food_menu_tbl_feedback_tble_rest_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('restaurant_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('type_of_restaurant', models.CharField(max_length=50)),
                ('authirised_person', models.CharField(max_length=50)),
                ('no_of_staff', models.IntegerField()),
                ('photo', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'restaurant_account',
            },
        ),
    ]
