# Generated by Django 4.2.2 on 2023-09-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_restaurant_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_accounts',
            },
        ),
    ]
