# Generated by Django 4.2.2 on 2023-09-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_tbl_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_menu',
            name='cusion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
