# Generated by Django 4.2.2 on 2023-09-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_food_menu_cusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_item',
            name='cooking_time',
            field=models.CharField(max_length=50),
        ),
    ]
