# Generated by Django 4.2.2 on 2023-09-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_food_item_cooking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_item',
            old_name='type',
            new_name='type_of_food',
        ),
    ]
