# Generated by Django 4.2.2 on 2023-09-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_type_of_food_food_item_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_menu',
            old_name='cusion',
            new_name='cruises',
        ),
    ]
