# Generated by Django 4.2.2 on 2023-09-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_rename_cusion_food_menu_cruises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant_account',
            old_name='authirised_person',
            new_name='authorised_person',
        ),
    ]
