# Generated by Django 4.2.2 on 2023-09-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_offer_end_date_alter_offer_offer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='restaurant_id',
            new_name='restaurant_name',
        ),
    ]
