# Generated by Django 4.2.2 on 2023-09-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_rename_restaurant_name_offer_restaurant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='restaurant_id',
            new_name='restaurant_name',
        ),
    ]
