# Generated by Django 4.2.2 on 2023-09-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_rename_restaurant_id_offer_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.CharField(max_length=50),
        ),
    ]
