# Generated by Django 4.2.2 on 2023-09-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_offer_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_account',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
