# Generated by Django 4.2.2 on 2023-09-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_restaurant_account_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_account',
            name='photo',
            field=models.CharField(max_length=500),
        ),
    ]
