# Generated by Django 4.2.6 on 2023-10-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_restaurant_account_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=50)),
                ('menu_name', models.CharField(max_length=50)),
                ('menu_item_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('photo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tbl_cart',
            },
        ),
    ]
