# Generated by Django 4.2.6 on 2023-10-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_tbl_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_cart',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='tbl_cart',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
