# Generated by Django 4.2.6 on 2023-10-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_rename_total_price_tbl_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cart',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
