# Generated by Django 4.2.6 on 2023-10-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_tbl_cart_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=50)),
                ('menu_name', models.CharField(max_length=50)),
                ('menu_item_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tbl_order',
            },
        ),
    ]
