# Generated by Django 4.2.6 on 2023-10-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_tbl_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_order',
            old_name='menu_name',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='tbl_order',
            old_name='restaurant_name',
            new_name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='tbl_order',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='tbl_order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tbl_order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='tbl_order',
            name='resturant_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_order',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
