# Generated by Django 4.2.6 on 2023-10-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_tbl_cart_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cart',
            name='status',
            field=models.CharField(default='available', max_length=50),
        ),
    ]
